- name: Test
  hosts: all
  tasks:
    - name: python-pi installed
      apt:
        name: python-pip
        state: present

    - name: Docker-py is present
      pip: name=docker-py state=present

    - name: Application container
      docker_container:
        name: motioneye
        image: vividboarder/rpi-motioneye
        state: present
